/**
 * generated by Xtext 2.18.0.M3
 */
package it.unibo.xtextIntro20.iot.impl;

import it.unibo.xtextIntro20.iot.IotPackage;
import it.unibo.xtextIntro20.iot.Request;

import org.eclipse.emf.ecore.EClass;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Request</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class RequestImpl extends MessageImpl implements Request
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected RequestImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return IotPackage.Literals.REQUEST;
  }

} //RequestImpl
