/* Generated by AN DISI Unibo */ 
package it.unibo.ctxBls
import it.unibo.kactor.QakContext
import it.unibo.kactor.sysUtil
import kotlinx.coroutines.runBlocking

fun main() = runBlocking {
	QakContext.createContexts(
	        "10.200.103.164", this, "sysexample.pl", "sysRules.pl"
	)
}

