/**
 * generated by Xtext 2.18.0.M3
 */
package it.unibo.xtextIntro20.ui.contentassist;

import it.unibo.xtextIntro20.ui.contentassist.AbstractIotProposalProvider;

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
@SuppressWarnings("all")
public class IotProposalProvider extends AbstractIotProposalProvider {
}
