/*
 * generated by Xtext 2.18.0.M3
 */
package it.unibo.xtextIntro20


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class IotStandaloneSetup extends IotStandaloneSetupGenerated {

	def static void doSetup() {
		new IotStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
