/**
 * generated by Xtext 2.18.0.M3
 */
package it.unibo.xtextIntro20.ide;

import it.unibo.xtextIntro20.ide.AbstractIotIdeModule;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class IotIdeModule extends AbstractIotIdeModule {
}
