/* Generated by AN DISI Unibo */ 
package it.unibo.actor1

import it.unibo.kactor.*
import alice.tuprolog.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
	
class Actor1 ( name: String, scope: CoroutineScope ) : ActorBasicFsm( name, scope){
 	
	override fun getInitialState() : String{
		return "s0"
	}
		
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		return { //this:ActionBasciFsm
				state("s0") { //this:State
					action { //it:State
					}
					 transition( edgeName="goto",targetState="work", cond=doswitch() )
				}	 
				state("work") { //this:State
					action { //it:State
						println("			actor1 waiting as an observer ...")
					}
					 transition(edgeName="t01",targetState="showInfo",cond=whenEvent("info"))
				}	 
				state("showInfo") { //this:State
					action { //it:State
						println("$name in ${currentState.stateName} | $currentMsg")
						updateCoapResource( currentMsg.toString() )
					}
					 transition( edgeName="goto",targetState="work", cond=doswitch() )
				}	 
			}
		}
}
