/* Generated by AN DISI Unibo */ 
package it.unibo.smartperceiver

import it.unibo.kactor.*
import alice.tuprolog.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
	
class Smartperceiver ( name: String, scope: CoroutineScope ) : ActorBasicFsm( name, scope){
 	
	override fun getInitialState() : String{
		return "s0"
	}
		
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		return { //this:ActionBasciFsm
				state("s0") { //this:State
					action { //it:State
						println("perceiver start")
					}
					 transition(edgeName="t06",targetState="handleEvent",cond=whenEvent("obstacle"))
					transition(edgeName="t07",targetState="handleEvent",cond=whenEvent("alarm"))
				}	 
				state("handleEvent") { //this:State
					action { //it:State
						println("perceiver handleEvent ")
						println("$name in ${currentState.stateName} | $currentMsg")
					}
					 transition(edgeName="t08",targetState="handleEvent",cond=whenEvent("obstacle"))
					transition(edgeName="t09",targetState="handleEvent",cond=whenEvent("alarm"))
				}	 
			}
		}
}
