/**
 * generated by Xtext 2.18.0.M3
 */
package it.unibo.xtextIntro20.validation;

import it.unibo.xtextIntro20.validation.AbstractIotValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class IotValidator extends AbstractIotValidator {
}
