/* Generated by AN DISI Unibo */ 
package it.unibo.onestpcaller

import it.unibo.kactor.*
import alice.tuprolog.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
	
class Onestpcaller ( name: String, scope: CoroutineScope ) : ActorBasicFsm( name, scope){
 	
	override fun getInitialState() : String{
		return "s0"
	}
		
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		return { //this:ActionBasciFsm
				state("s0") { //this:State
					action { //it:State
						delay(1000) 
						println("onestpcaller doing a step")
						request("step", "step(1000)" ,"smartrobot" )  
					}
					 transition(edgeName="t07",targetState="anotherStep",cond=whenReply("stepdone"))
					transition(edgeName="t08",targetState="stepFailed",cond=whenReply("stepfail"))
				}	 
				state("anotherStep") { //this:State
					action { //it:State
						println("onestpcaller doing another step")
						request("step", "step(1000)" ,"smartrobot" )  
						delay(500) 
						forward("stop", "stop" ,"smartrobot" ) 
					}
					 transition(edgeName="t09",targetState="endOfStep",cond=whenReply("stepdone"))
					transition(edgeName="t010",targetState="stepFailed",cond=whenReply("stepfail"))
				}	 
				state("endOfStep") { //this:State
					action { //it:State
						println("onestpcaller: onestep DONE")
					}
				}	 
				state("stepFailed") { //this:State
					action { //it:State
						if( checkMsgContent( Term.createTerm("stepfail(DURATION)"), Term.createTerm("onestepfail"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								println("onestpcaller stepFail Duration=${payloadArg(0)} ")
						}
					}
				}	 
			}
		}
}
