/*
 * generated by Xtext 2.18.0.M3
 */
package it.unibo.xtextIntro20.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.validation.AbstractDeclarativeValidator;

public abstract class AbstractIotValidator extends AbstractDeclarativeValidator {
	
	@Override
	protected List<EPackage> getEPackages() {
		List<EPackage> result = new ArrayList<EPackage>();
		result.add(it.unibo.xtextIntro20.iot.IotPackage.eINSTANCE);
		return result;
	}
}
