/* Generated by AN DISI Unibo */ 
package it.unibo.onestepahead

import it.unibo.kactor.*
import alice.tuprolog.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
	
class Onestepahead ( name: String, scope: CoroutineScope ) : ActorBasicFsm( name, scope){
 	
	override fun getInitialState() : String{
		return "s0"
	}
		
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		 
		var StepTime = 1000L;  
		var Duration=0 
		return { //this:ActionBasciFsm
				state("s0") { //this:State
					action { //it:State
						println("onestepahead ready to go ...")
					}
					 transition(edgeName="t00",targetState="doStep",cond=whenDispatch("onestep"))
				}	 
				state("doStep") { //this:State
					action { //it:State
						println("$name in ${currentState.stateName} | $currentMsg")
						if( checkMsgContent( Term.createTerm("onestep(DURATION)"), Term.createTerm("onestep(T)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								StepTime = payloadArg(0).toLong()
								startTimer()
								forward("cmd", "cmd(w)" ,"basicrobotinmind" ) 
						}
						stateTimer = TimerActor("timer_doStep", 
							scope, context!!, "local_tout_onestepahead_doStep", StepTime )
					}
					 transition(edgeName="t01",targetState="endStep",cond=whenTimeout("local_tout_onestepahead_doStep"))   
					transition(edgeName="t02",targetState="stepFail",cond=whenEvent("obstacle"))
				}	 
				state("endStep") { //this:State
					action { //it:State
						forward("cmd", "cmd(h)" ,"basicrobotinmind" ) 
						println("onestepahead: onestep DONE")
					}
					 transition( edgeName="goto",targetState="s0", cond=doswitch() )
				}	 
				state("stepFail") { //this:State
					action { //it:State
						Duration=getDuration()
						println("onestepahead stepFail Duration=$Duration ")
					}
					 transition( edgeName="goto",targetState="s0", cond=doswitch() )
				}	 
			}
		}
}
