package it.unibo.xtextIntro20.generator;

import org.eclipse.xtext.generator.IFileSystemAccess;

@SuppressWarnings("all")
public class GenUtils {
  public static IFileSystemAccess curFsa;
  
  public static final String logo = "/* Generated by AN DISI Unibo */ ";
  
  public static String packageName = "";
  
  public static Object fileExtenstion = null;
  
  public static String pubSubServAddr = null;
  
  public static Object setFileExtension(final String fe) {
    return GenUtils.fileExtenstion = fe;
  }
  
  public static String setPbSubServer(final String addr) {
    return GenUtils.pubSubServAddr = addr;
  }
  
  public static String setPackageName(final String applName) {
    return GenUtils.packageName = ("it.unibo." + applName);
  }
  
  public static IFileSystemAccess setFsa(final IFileSystemAccess fsa) {
    return GenUtils.curFsa = fsa;
  }
  
  /**
   * Utility to generate a file
   */
  public static void genFile(final String packageName, final String name, final String suffix, final CharSequence contents) {
    String _replace = packageName.replace(".", "/");
    String _plus = (_replace + "/");
    String _plus_1 = (_plus + name);
    String _plus_2 = (_plus_1 + ".");
    String fName = (_plus_2 + suffix);
    GenUtils.curFsa.generateFile(fName, contents);
  }
  
  public static void genFileRoot(final String packageName, final String name, final String suffix, final CharSequence contents) {
    String sysName = packageName.replace(".", "/");
    String fName = ((((("../" + sysName) + "/") + name) + ".") + suffix);
    GenUtils.curFsa.generateFile(fName, contents);
  }
  
  public static void genFileDir(final String dir, final String packageName, final String name, final String suffix, final CharSequence contents) {
    String sysName = packageName.replace(".", "/");
    String fName = "";
    int _length = sysName.length();
    boolean _greaterThan = (_length > 0);
    if (_greaterThan) {
      fName = ((((((dir + "/") + sysName) + "/") + name) + ".") + suffix);
    } else {
      fName = ((((dir + "/") + name) + ".") + suffix);
    }
    GenUtils.curFsa.generateFile(fName, contents);
  }
  
  public static void genFileSrcDir(final String packageName, final String name, final String suffix, final CharSequence contents) {
    System.out.println((((" +++++ generate " + name) + " packageName=") + packageName));
    String sysName = packageName.replace(".", "/");
    String fName = "";
    int _length = sysName.length();
    boolean _greaterThan = (_length > 0);
    if (_greaterThan) {
      fName = ((((("../src/" + sysName) + "/") + name) + ".") + suffix);
    } else {
      fName = ((("../src/" + name) + ".") + suffix);
    }
    System.out.println((" +++++ generate " + fName));
    GenUtils.curFsa.generateFile(fName, contents);
  }
}
