/* Generated by AN DISI Unibo */ 
package it.unibo.localcaller1

import it.unibo.kactor.*
import alice.tuprolog.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
	
class Localcaller1 ( name: String, scope: CoroutineScope ) : ActorBasicFsm( name, scope){
 	
	override fun getInitialState() : String{
		return "s0"
	}
		
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		return { //this:ActionBasciFsm
				state("s0") { //this:State
					action { //it:State
						println("localcaller1 sending a dispatch ")
						forward("userCmd", "userCmd(a)" ,"resource" ) 
						println("localcaller1 sending a request ")
						request("cmd", "cmd(a)" ,"resource" )  
					}
					 transition( edgeName="goto",targetState="work", cond=doswitch() )
				}	 
				state("work") { //this:State
					action { //it:State
						println("localcaller1 work .... ")
					}
					 transition(edgeName="t03",targetState="handleReply",cond=whenReply("replytocmd"))
				}	 
				state("handleReply") { //this:State
					action { //it:State
						println("       --- localcaller1 handleReply ")
						println("$name in ${currentState.stateName} | $currentMsg")
						println("       --- localcaller1 handleReply and terminates")
					}
				}	 
			}
		}
}
