/* Generated by AN DISI Unibo */ 
package it.unibo.ctxRadarGui
import it.unibo.kactor.QakContext
import it.unibo.kactor.sysUtil
import kotlinx.coroutines.runBlocking

fun main() = runBlocking {
	QakContext.createContexts(
	        "somehost", this, "sprint1analysismqtt.pl", "sysRules.pl"
	)
}

