/**
 * generated by Xtext 2.18.0.M3
 */
package it.unibo.xtextIntro20;

import it.unibo.xtextIntro20.AbstractIotRuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class IotRuntimeModule extends AbstractIotRuntimeModule {
}
