/**
 * generated by Xtext 2.18.0.M3
 */
package it.unibo.xtextIntro20;

import it.unibo.xtextIntro20.IotStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class IotStandaloneSetup extends IotStandaloneSetupGenerated {
  public static void doSetup() {
    new IotStandaloneSetup().createInjectorAndDoEMFRegistration();
  }
}
