/* Generated by AN DISI Unibo */ 
package it.unibo.robotcaller

import it.unibo.kactor.*
import alice.tuprolog.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
	
class Robotcaller ( name: String, scope: CoroutineScope ) : ActorBasicFsm( name, scope){
 	
	override fun getInitialState() : String{
		return "s0"
	}
		
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		var Counter = 0
		return { //this:ActionBasciFsm
				state("s0") { //this:State
					action { //it:State
					}
				}	 
				state("eventEmit") { //this:State
					action { //it:State
						delay(30000) 
						Counter++
						println("robotcaller emits tick $Counter")
						emit("tick", "tick($Counter)" ) 
					}
					 transition( edgeName="goto",targetState="eventEmit", cond=doswitch() )
				}	 
			}
		}
}
