/* Generated by AN DISI Unibo */ 
package it.unibo.robotcaller

import it.unibo.kactor.*
import alice.tuprolog.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
	
class Robotcaller ( name: String, scope: CoroutineScope ) : ActorBasicFsm( name, scope){
 	
	override fun getInitialState() : String{
		return "s0"
	}
		
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		return { //this:ActionBasciFsm
				state("s0") { //this:State
					action { //it:State
						println("robotCallerSimulator start")
						forward("step", "step(1000)" ,"basicrobot" ) 
						delay(1100) 
						forward("cmd", "cmd(a)" ,"basicrobot" ) 
						delay(500) 
						forward("cmd", "cmd(d)" ,"basicrobot" ) 
						delay(500) 
						forward("step", "step(1000)" ,"basicrobot" ) 
						delay(200) 
						forward("stop", "stop(1)" ,"basicrobot" ) 
						forward("cmd", "cmd(s)" ,"basicrobot" ) 
						delay(1400) 
						forward("cmd", "cmd(h)" ,"basicrobot" ) 
					}
				}	 
			}
		}
}
