/* Generated by AN DISI Unibo */ 
package it.unibo.user

import it.unibo.kactor.*
import alice.tuprolog.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
	
class User ( name: String, scope: CoroutineScope ) : ActorBasicFsm( name, scope){
 	
	override fun getInitialState() : String{
		return "s0"
	}
		
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		return { //this:ActionBasciFsm
				state("s0") { //this:State
					action { //it:State
						println("user forward userCmd ")
						forward("userCmd", "userCmd(1)" ,"resource" ) 
						delay(1000) 
						println("user request cmd ")
						request("cmd", "cmd(a)" ,"resource" )  
					}
					 transition(edgeName="t00",targetState="handleReply",cond=whenReply("replytocmd"))
				}	 
				state("handleReply") { //this:State
					action { //it:State
						println("       --- handleReply ")
						println("$name in ${currentState.stateName} | $currentMsg")
						println("       --- handleReply ")
					}
				}	 
			}
		}
}
