/**
 * generated by Xtext 2.18.0.M3
 */
package it.unibo.xtextIntro20.ui.outline;

import org.eclipse.xtext.ui.editor.outline.impl.DefaultOutlineTreeProvider;

/**
 * Customization of the default outline structure.
 * 
 * See https://www.eclipse.org/Xtext/documentation/310_eclipse_support.html#outline
 */
@SuppressWarnings("all")
public class IotOutlineTreeProvider extends DefaultOutlineTreeProvider {
}
