/* Generated by AN DISI Unibo */ 
package it.unibo.smartrobot

import it.unibo.kactor.*
import alice.tuprolog.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
	
class Smartrobot ( name: String, scope: CoroutineScope ) : ActorBasicFsm( name, scope){
 	
	override fun getInitialState() : String{
		return "s0"
	}
		
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		 
		var StepTime = 0L 
		var Duration = 0 
		var WithResource = true
		var DoStepAnswer = false	//avoid to send answer after a step
		return { //this:ActionBasciFsm
				state("s0") { //this:State
					action { //it:State
						println("smartrobot starts")
						forward("cmd", "cmd(l)" ,"basicrobot" ) 
						delay(1000) 
						forward("cmd", "cmd(h)" ,"basicrobot" ) 
						forward("cmd", "cmd(r)" ,"basicrobot" ) 
						delay(1000) 
						forward("cmd", "cmd(h)" ,"basicrobot" ) 
						println("smartrobot started")
					}
					 transition( edgeName="goto",targetState="activateResource", cond=doswitchGuarded({WithResource}) )
					transition( edgeName="goto",targetState="work", cond=doswitchGuarded({! WithResource}) )
				}	 
				state("activateResource") { //this:State
					action { //it:State
						kotlincode.resServer.init(myself)
						kotlincode.coapSupport.init( "coap://localhost:5683"  )
						delay(1000) 
						kotlincode.resourceObserver.init( "coap://localhost:5683", "robot/pos"  )
					}
					 transition( edgeName="goto",targetState="work", cond=doswitch() )
				}	 
				state("work") { //this:State
					action { //it:State
					}
					 transition(edgeName="s00",targetState="handleCmd",cond=whenDispatch("cmd"))
					transition(edgeName="s01",targetState="doStepNoAnswer",cond=whenDispatch("step"))
					transition(edgeName="s02",targetState="doStepWithAnswer",cond=whenRequest("step"))
					transition(edgeName="s03",targetState="handleStopNotExpected",cond=whenDispatch("stop"))
					transition(edgeName="s04",targetState="ignoreObstacle",cond=whenEvent("obstacle"))
					transition(edgeName="s05",targetState="updateDistanceResource",cond=whenEvent("polar"))
				}	 
				state("updateDistanceResource") { //this:State
					action { //it:State
						println("$name in ${currentState.stateName} | $currentMsg")
						if( checkMsgContent( Term.createTerm("polar(D,Angle)"), Term.createTerm("polar(D,A)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								if(WithResource){ kotlincode.coapSupport.updateResource(myself ,"robot/sonar", "distance(${payloadArg(0)})" )
								 }
						}
					}
					 transition( edgeName="goto",targetState="work", cond=doswitch() )
				}	 
				state("handleStopNotExpected") { //this:State
					action { //it:State
						println("smartrobot | WARNING: the stop command should not be sent here")
					}
					 transition( edgeName="goto",targetState="work", cond=doswitch() )
				}	 
				state("ignoreObstacle") { //this:State
					action { //it:State
						println("smartrobot | IGNORE obstacle event")
					}
					 transition( edgeName="goto",targetState="work", cond=doswitch() )
				}	 
				state("handleCmd") { //this:State
					action { //it:State
						println("$name in ${currentState.stateName} | $currentMsg")
						if( checkMsgContent( Term.createTerm("cmd(X)"), Term.createTerm("cmd(X)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								var Move = payloadArg(0)
								forward("cmd", "cmd($Move)" ,"basicrobot" ) 
								if(( WithResource )){ kotlincode.coapSupport.updateResource(myself ,"robot/pos", "u$Move" )
								 }
						}
					}
					 transition( edgeName="goto",targetState="work", cond=doswitch() )
				}	 
				state("doStepNoAnswer") { //this:State
					action { //it:State
						if( checkMsgContent( Term.createTerm("step(DURATION)"), Term.createTerm("step(T)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								 StepTime = payloadArg(0).toLong(); DoStepAnswer = false 
						}
					}
					 transition( edgeName="goto",targetState="doStep", cond=doswitch() )
				}	 
				state("doStepWithAnswer") { //this:State
					action { //it:State
						if( checkMsgContent( Term.createTerm("step(DURATION)"), Term.createTerm("step(T)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								StepTime = payloadArg(0).toLong(); DoStepAnswer = true 
						}
					}
					 transition( edgeName="goto",targetState="doStep", cond=doswitch() )
				}	 
				state("doStep") { //this:State
					action { //it:State
						println("smartrobot | doStep StepTime=$StepTime ")
						 startTimer()
						forward("cmd", "cmd(w)" ,"basicrobot" ) 
						stateTimer = TimerActor("timer_doStep", 
							scope, context!!, "local_tout_smartrobot_doStep", StepTime )
					}
					 transition(edgeName="t06",targetState="endStep",cond=whenTimeout("local_tout_smartrobot_doStep"))   
					transition(edgeName="t07",targetState="stepStop",cond=whenDispatch("stop"))
					transition(edgeName="t08",targetState="stepFail",cond=whenEvent("obstacle"))
				}	 
				state("endStep") { //this:State
					action { //it:State
						forward("cmd", "cmd(h)" ,"basicrobot" ) 
						println("smartrobot | step DONE")
						if(WithResource){ kotlincode.coapSupport.updateResource(myself ,"robot/pos", "up" )
						 }
						if(DoStepAnswer){ answer("step", "stepdone", "stepdone(ok)"   )  
						 }
					}
					 transition( edgeName="goto",targetState="work", cond=doswitch() )
				}	 
				state("stepStop") { //this:State
					action { //it:State
						Duration=getDuration()
						forward("cmd", "cmd(h)" ,"basicrobot" ) 
						if(WithResource){ kotlincode.coapSupport.updateResource(myself ,"robot/pos", "ustop" )
						 }
						if(DoStepAnswer){ answer("step", "stepfail", "stepfail($Duration,stopped)"   )  
						 }
						println("smartrobot | stepStop Duration=$Duration DoStepAnswer=$DoStepAnswer ")
					}
					 transition( edgeName="goto",targetState="work", cond=doswitch() )
				}	 
				state("stepFail") { //this:State
					action { //it:State
						Duration=getDuration()
						answer("step", "stepfail", "stepfail($Duration,obstacle)"   )  
						if(DoStepAnswer){ println("smartrobot | stepFail Duration=$Duration ")
						 }
					}
					 transition( edgeName="goto",targetState="work", cond=doswitch() )
				}	 
			}
		}
}
