/*
 * generated by Xtext 2.18.0.M3
 */
package it.unibo.xtextIntro20.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class IotAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("it/unibo/xtextIntro20/parser/antlr/internal/InternalIot.tokens");
	}
}
