/**
 * generated by Xtext 2.18.0.M3
 */
package it.unibo.xtextIntro20.iot;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Dispatch</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see it.unibo.xtextIntro20.iot.IotPackage#getDispatch()
 * @model
 * @generated
 */
public interface Dispatch extends Message
{
} // Dispatch
