/**
 * generated by Xtext 2.18.0.M3
 */
package it.unibo.xtextIntro20.iot;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Request</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see it.unibo.xtextIntro20.iot.IotPackage#getRequest()
 * @model
 * @generated
 */
public interface Request extends Message
{
} // Request
